[package]
name = "script-gibz"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Peter Gisler"]
license = "MIT-0"
description = "GIBZ Typst template + components (tasks, hints, supplementary, code box) with DE/EN i18n and a clean flat API."
repository = "https://gitlab.com/GIBZ/public/typst-template"
keywords = ["GIBZ", "education", "teaching", "template", "course"]
categories = ["layout", "components", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
